/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafeRouteImport } from './routes/safe'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AlertRouteImport } from './routes/alert'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiDetectRouteImport } from './routes/api/detect'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRoute = SafeRouteImport.update({
  id: '/safe',
  path: '/safe',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDetectRoute = ApiDetectRouteImport.update({
  id: '/api/detect',
  path: '/api/detect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/safe': typeof SafeRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/api/detect': typeof ApiDetectRoute
  '/api/history': typeof ApiHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/safe': typeof SafeRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/api/detect': typeof ApiDetectRoute
  '/api/history': typeof ApiHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert': typeof AlertRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/safe': typeof SafeRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/api/detect': typeof ApiDetectRoute
  '/api/history': typeof ApiHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert'
    | '/history'
    | '/learn'
    | '/login'
    | '/monitoring'
    | '/safe'
    | '/settings'
    | '/upload'
    | '/api/detect'
    | '/api/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert'
    | '/history'
    | '/learn'
    | '/login'
    | '/monitoring'
    | '/safe'
    | '/settings'
    | '/upload'
    | '/api/detect'
    | '/api/history'
  id:
    | '__root__'
    | '/'
    | '/alert'
    | '/history'
    | '/learn'
    | '/login'
    | '/monitoring'
    | '/safe'
    | '/settings'
    | '/upload'
    | '/api/detect'
    | '/api/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertRoute: typeof AlertRoute
  HistoryRoute: typeof HistoryRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  SafeRoute: typeof SafeRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  ApiDetectRoute: typeof ApiDetectRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe': {
      id: '/safe'
      path: '/safe'
      fullPath: '/safe'
      preLoaderRoute: typeof SafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert': {
      id: '/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/detect': {
      id: '/api/detect'
      path: '/api/detect'
      fullPath: '/api/detect'
      preLoaderRoute: typeof ApiDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertRoute: AlertRoute,
  HistoryRoute: HistoryRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  SafeRoute: SafeRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  ApiDetectRoute: ApiDetectRoute,
  ApiHistoryRoute: ApiHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
